<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!--
  Copyright (c) 2026 e-Yantra, IIT Bombay. All rights reserved.
  These simulation files and source code are the intellectual property of e-Yantra,
  IIT Bombay, provided solely for eYRC 2026-27 (Theme: Hola The Explorer).
  Sharing or redistribution of this material, in whole or in part, is not permitted.
-->
<package format="3">
  <name>shape_interface</name>
  <version>0.0.0</version>
  <description>Shape.msg and GetShape.srv interfaces shared by task_1c and its shape service/controller.</description>
  <maintainer email="srivenkateshwar@e-yantra.org">neo-erts</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <exec_depend>rosidl_default_runtime</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
